version: '3'
services:
    mysql:
        image: mysql
        container_name: mysql-test
        hostname: mysql-test
        environment:
            MYSQL_ROOT_PASSWORD: Root123456
            TZ: Asia/Shanghai
        ports:
            - 3306:3306
        volumes:
          - ./data:/var/lib/mysql:z
        command:
            --max_connections=1000
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
